/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SPIM_1.h"
#include "SPIM_1_PVT.h"
#include "MISO_aliases.h"
#include "MISO.h"
#include "MOSI_aliases.h"
#include "MOSI.h"
#include "SCLK_aliases.h"
#include "SCLK.h"
#include "SS_aliases.h"
#include "SS.h"
#include "DC_aliases.h"
#include "DC.h"
#include "RST_aliases.h"
#include "RST.h"
#include "LED_aliases.h"
#include "LED.h"
#include "Input_Data_aliases.h"
#include "Input_Data.h"
#include "Buzzer_aliases.h"
#include "Buzzer.h"
#include "Data_Available_aliases.h"
#include "Data_Available.h"
#include "TouchScreen.h"
#include "SPIM_1_IntClock.h"
#include "TouchScreen_AMux.h"
#include "TouchScreen_xm_aliases.h"
#include "TouchScreen_xm.h"
#include "TouchScreen_xp_aliases.h"
#include "TouchScreen_xp.h"
#include "TouchScreen_ym_aliases.h"
#include "TouchScreen_ym.h"
#include "TouchScreen_yp_aliases.h"
#include "TouchScreen_yp.h"
#include "TouchScreen_ADC.h"
#include "TouchScreen_ADC_AMux.h"
#include "TouchScreen_ADC_Ext_CP_Clk.h"
#include "TouchScreen_ADC_IRQ.h"
#include "TouchScreen_ADC_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

